
  name: ci
  on: 
    push:
      branches: [ master ]
  jobs:
    lint:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - uses: stefanoeb/eslint-action@1.0.2
          with:
            files: /src
    docker:
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - uses: actions/checkout@v3
          name: Check out code
      
        - uses: mr-smithers-excellent/docker-build-push@v6
          name: Build & push Docker image
          with:
            image: filok94/api_hand
            tags: v1, latest
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

